language: node_js
node_js:
  - '0.10'
sudo: false
script: travis_retry npm test
env:
  global:
    - secure: Rcas3twM7Kj9Hoau73JA8ebDhjeh4F3ldaYPKYuWqITRAQoinaU6IoPXD9+DQoGMkZZ7AXQ9GaIcTXvMon1+rkbPRu/c/VHIpKbFdVMKVOe8BBmcqvrE7+xUTYJjI1pEwaZ7DZRE9Od5N1DoCkypzzq7+ykrQRcL6WGNZLnIp9k=
    - secure: P/k68KjN+lPnKEguSdOt/6k7AWKFZY1EzdkcFtGAtekn+YVnNzUgmDO4d5B6B4YvyIejvd86T/qsE4dECubtaqlWsj/Afi0n08zq8USRDPJQkawe/cifUeolHA5OZoZJx6jYaH/4ybUIM3158d8EwLLTpayxVnybjEPsXiqHL/0=
